name: "Set Issue Label and Assignee"
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: Naturalclar/issue-action@f229cda
        if: github.event.pull_request.user.login == 'auto-machine' && contains(github.event.pull_request.title, 'upgrade projen')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          title-or-body: "title"
          parameters: >
            [
            {"keywords":["upgrade projen"],"labels":["projen/upgrade", "auto-merge"],"assignees":["guan840912"]}
            ]
      - uses: Naturalclar/issue-action@f229cda
        if: github.event.pull_request.user.login == 'auto-machine' && contains(github.event.pull_request.title, 'yarn upgrade')
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          title-or-body: "title"
          parameters: >
            [
            {"keywords":["yarn upgrade"],"labels":["yarn/upgrade", "auto-merge"],"assignees":["guan840912"]}
            ]
          
